### PR TITLE
Preserve order when using JSON output

### LINKED ISSUE #241: JSON output is sorted
When converting the objects to JSON here: https://github.com/omerbenamram/evtx/blob/master/src/evtx_record.rs#L101-L105

This serde_json function is sorting the results when returning the data. Serde_json has a feature to preserve the order and not sort data, mentioned here: https://docs.rs/serde_json/latest/serde_json/enum.Value.html#variant.Object

The issue with sorting data, is that sometimes under 'EventData', the parameters are occasionally "Named" rather than just param1, param2, etc. If you try to fill in the sorted "named" variables, as opposed to the correct ordering, the message strings no longer make any sense.

For an example, here is the difference between between JSON and XML output for the same event:
JSON:
image

XML:
image

The way messages are stored and expected to be parsed is the same way they are stored in the raw data. For example, it will expect you to fill in the first parameter followed by the 4th parameter. The way JSON is currently returning data, all of the parameters will be out of order, and it will not be possible to fill in the event message data correctly.

### PR DESCRIPTION
**Pull request by ac-rn**
Fixes #241

### CODE REVIEW

**Comment by omerbenamram** [comment]
Interesting! I'll need to update the snapshots to make this pass the tests nicely, thanks for this!

**Comment by ac-rn** [comment]
@omerbenamram tests should be fixed now!

**Comment by ac-rn** [comment]
apologies @omerbenamram all the remaining tests should now be fixed, and it does successfully build for me now

**Comment by omerbenamram** [comment]
@ac-rn thanks again for this contribution!

**Pull request merged**
